ALTER TABLE notes ADD COLUMN pinned BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE notes ADD COLUMN archived BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE notes ADD COLUMN updated_at TIMESTAMP;

UPDATE notes
SET updated_at = COALESCE(created_at, CURRENT_TIMESTAMP);

ALTER TABLE notes ALTER COLUMN updated_at SET NOT NULL;
