global:
  scrape_interval: 15s

scrape_configs:
  - job_name: backend-actuator
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - jorge-backend:8080

  - job_name: postgres-exporter
    static_configs:
      - targets:
          - jorge-postgres-exporter:9187

  - job_name: node-exporter
    static_configs:
      - targets:
          - jorge-node-exporter:9100

  - job_name: loki
    static_configs:
      - targets:
          - jorge-loki:3100

  - job_name: promtail
    static_configs:
      - targets:
          - jorge-promtail:9080

  - job_name: victoriametrics-self
    static_configs:
      - targets:
          - jorge-victoriametrics:8428
