server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: podman-journald-system
    journal:
      path: /var/log/journal
      max_age: 1h
      labels:
        job: podman-journald
    relabel_configs:
      - action: keep
        source_labels: ['__journal_container_name']
        regex: .+
      - source_labels: ['__journal__hostname']
        target_label: host
      - source_labels: ['__journal_container_name']
        target_label: container
      - source_labels: ['__journal_container_id_full']
        target_label: container_id
      - source_labels: ['__journal__systemd_unit']
        target_label: systemd_unit
      - source_labels: ['__journal_priority_keyword']
        target_label: level

  - job_name: podman-journald-rootless
    journal:
      path: /run/user/journal
      max_age: 1h
      labels:
        job: podman-journald
    relabel_configs:
      - action: keep
        source_labels: ['__journal_container_name']
        regex: .+
      - source_labels: ['__journal__hostname']
        target_label: host
      - source_labels: ['__journal_container_name']
        target_label: container
      - source_labels: ['__journal_container_id_full']
        target_label: container_id
      - source_labels: ['__journal__systemd_unit']
        target_label: systemd_unit
      - source_labels: ['__journal_priority_keyword']
        target_label: level
